@E2EAll
Feature: Admin ogrenci olusturma Testi

@UI
  Scenario Outline: okul sitesinde Admin Basarili sekilde ogrenci olusturabilmeli
    Given Kullanici okul sayfasina gider...
    Then Kullanici Login butonuna tiklar...
    When Kullanici Admin hesabi ile Sing in yapar...
    And Kullanici Menua tiklar...
    And Kullanici Student Management tiklar...
    And Kullanici tum alanlarin bos oldugunu test eder...
    And Kullanici Choose Teacher yapar...
    Then Kullanici "<Name>" alanina gecerli bir ad girer...
    And Kullanici Name alaninin bos olmadigini test eder...
    Then Kullanici "<surname>" alanina gecerli bir surname girer...
    Then Kullanici "<Birth Place>" alanina gecerli bir birthplace girer...
    And Kullanici Birth Place alaninin bos olmadigini test eder...
    Then Kullanici "<Email>" alanina gecerli bir email girer...
    And Kullanici Email alaninin bos olmadigini test eder...
    And Kullanici "<Phone>" kutusuna gecerli bir telefon numarasi girer...
    And Kullanici Phone kutusunun bos olmadigini test eder...
    Then Kullanici Gender_e_datayi_girer...
    And Kullanici Gender seçeneginin bos olmadigini test eder...
    Then Kullanici "<Date Of Birth>" kutusuna geçerli bir doğum tarihi girer...
    And Kullanici Date Of Birth kutusunun bos olmadigini test eder...
    Then Kullanici "<Ssn>" kutusuna gecerli bir SSN girer...
    And Kullanici Ssn kutusunun bos olmadigini test eder...
    Then Kullanici "<User Name>" kutusuna gecerli bir User Name girer...
    And Kullanici User Name kutusunun bos olmadigini test eder...
    Then Kullanici "<father name>" kutusuna gecerli bir fathername girer...
    And Kullanici father name kutusunun bos olmadigini test eder...
    Then Kullanici"<mother name>"kutusuna gecerli bir mothername girer...
    And Kullanici mother name kutusunun bos olmadigini test eder...
    Then Kullanici "<Password>" kutusuna buyuk harf kucuk harf ve rakam iceren en az 8 karakterli bir sifreyi girer...
    Then Kullanici submit e tiklar...
    And Kullanici Student save succesfully uyarisini gorur...
    And Kullanici sayfayi kapatir...

    Examples:
      | Name      | surname | Birth Place | Email | Phone | Date Of Birth | Ssn   | User Name | father name | mother name | Password     |
      | Project10 | Team02  | Turkey      | faker | faker | 01-01-1992    | faker | faker     | fathrname   | motername   | AdminTeam02. |

  @API
  Scenario: Admin ogrenci olusturuldugunu API ile test edebilir
    Given Student eklemek icin Post request hazirligi yapilir...
    When Admin eklemek icin student request gonderilir...
    Then Student bilgileri dogrulanir
    And student verisi silinir...
    Then silme dogrulama islemi yapilir...

  @DB
 Scenario: Database
    Given Kayitli ogrencinin UserId bilgisi ile sorgu yapilir
    Then Ogrenci bilgilerinin database dogrulamasi yapilir